name: Tag List Annotation

on: 
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  annotate-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    name: Annotates pull request with table of repository tags
    steps:
      - name: Annotate PR
        uses: sheeley820/tag-list-action@main
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}