name: Tag List Annotation

on:
  - workflow_dispatch

jobs:
  annotate-pr-local:
    runs-on: ubuntu-latest
    name: Annotates pull request with table of repository tags
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Annotate PR
        uses: ./
        with:
          path: "action"